#!/usr/bin/python

import database
import json
from datetime import datetime, timedelta
import time
import urllib,urllib2

debug = False

milDateFormat="%m/%d/%Y"
milDateTimeFormat="%m/%d/%Y %H:%M"

def tzOffset():
    timestamp = time.time()
    timeNow = datetime.fromtimestamp(timestamp)
    timeUtc = datetime.utcfromtimestamp(timestamp)
    
    if (timeNow<timeUtc):
        offsetStr="-"+str(timeUtc-timeNow)
    else:
        offsetStr="+"+str(timeNow-timeUtc)
    
    return offsetStr[:offsetStr.find(":")]
    

def getSunData(siteInfo,forDt):
    forDtStr = forDt.strftime(milDateFormat)
    if debug:
        print forDtStr
    tzStr = tzOffset()
    if debug:
        print tzStr
    # https://api.usno.navy.mil/rstt/oneday?date=5/15/2019&coords=35.134686,-120.562267&tz=-07
    url="https://api.usno.navy.mil/rstt/oneday?date="+forDtStr+"&coords="+siteInfo['lat']+','+siteInfo['lon']+"&tz="+tzStr
    if debug:
        print url

    try:
        response=urllib2.urlopen(url)
    except urllib2.HTTPError as e:
        # This means something went wrong.
        raise Exception('getSunData: {}'.format(e.code))

    responseData = json.loads(response.read().encode("utf-8"))
    if debug:
        print responseData['sundata']
        
    sunDict={}
    sunDict['sundate']=forDt

    for dataset in responseData['sundata']:
        if (dataset['phen']=='R'):
            sunDict['sunrise']=datetime.strptime(forDtStr+" "+dataset['time'],milDateTimeFormat)
        elif (dataset['phen']=='S'):
            sunDict['sunset']=datetime.strptime(forDtStr+" "+dataset['time'],milDateTimeFormat)
    
    return sunDict


today = datetime.now().date()
if debug:
    print "Date: "+today.strftime(milDateTimeFormat)

# dbConnection = database.connect()
# dbCursor = dbConnection.cursor()

siteInfo = database.getSiteInfo("dmalone")
savedSunData = database.getSunData(siteInfo)
if debug:
    print "Date: "+savedSunData['sundate'].strftime(milDateTimeFormat)


if (savedSunData['sundate']==None or savedSunData['sundate']!=today):
    todaySunData=getSunData(siteInfo,today)
    database.setSunData(siteInfo,todaySunData)

