#!/usr/bin/python

import database
import json
from datetime import datetime
import urllib2

debug = False

def getCurrentData(siteInfo):
    restURL = 'https://monitoringapi.solaredge.com/site/'+siteInfo['id']+'/overview?api_key='+siteInfo['apiKey']
    try:
        restResponse = urllib2.urlopen(restURL)
    except urllib2.HTTPError as e:
        # This means something went wrong.
        raise Exception('getCurrentData: {}'.format(e.code))
        
    overview = json.loads(restResponse.read().encode("utf-8"))
    
#     print overview

#     with open('overview.json', 'r') as file:
#         overview = json.load(file)

    overviewDict={}
    overviewDict['queryTime'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    overviewDict['lastUpdateTime'] = overview['overview']['lastUpdateTime'].encode("utf-8")
    overviewDict['currentPower'] = overview['overview']['currentPower']['power']
    overviewDict['lastDayEnergy'] = overview['overview']['lastDayData']['energy']
    overviewDict['lastMonthEnergy'] = overview['overview']['lastMonthData']['energy']
    overviewDict['lastYearEnergy'] = overview['overview']['lastYearData']['energy']
    overviewDict['lifetimeEnergy'] = overview['overview']['lifeTimeData']['energy']

    return overviewDict

#
# main
#

siteInfo = database.getSiteInfo("dmalone")

# maxLastUpdateTime = getLastUpdateTime(siteInfo)
lastData = database.getLastOverview(siteInfo)

currentData = getCurrentData(siteInfo)

if debug:
    print "last:"
    print lastData
    print "current:"
    print currentData
    
if (currentData['lastUpdateTime'] > lastData['lastUpdateTime']):
    database.insertOverview(siteInfo,currentData)
else:
    if debug:
        print "no update"

restData = database.getLastOverview(siteInfo)

with open(siteInfo['name']+'.json', 'w') as output:
    json.dump(lastData, output)