#!/usr/bin/python

import database
import sqlite3

conn = database.connect()

cursor = conn.cursor()

cursor.execute('''
CREATE TABLE overview
             (siteId            text,
              queryTime         text,
              lastUpdateTime    text,
              currentPower      real,
              lastDayEnergy     real,
              lastMonthEnergy   real,
              lastYearEnergy    real,
              lifetimeEnergy    real
             )
''')

cursor.execute('''
CREATE TABLE sites
             (id      text,
              name    text,
              apiKey  text,
              lat     text,
              lon     text
             )
''')

cursor.execute('''
CREATE TABLE sunData
             (siteId  text,
              date    text,
              sunrise text,
              sunset  text
             )
''')

conn.commit()
