#!/usr/bin/python
#
# updateSiteInfo
#

import database
import sys

# print len(sys.argv)

if ((len(sys.argv) != 2) and (len(sys.argv) != 6)):
    print "usage: "+sys.argv[0]+" <siteID> <name> <apiKey> <latitude> <longitude>"
    exit()

siteInfo = {}
siteInfo["id"] = sys.argv[1]
if (len(sys.argv) == 6):
    siteInfo["name"] = sys.argv[2]
    siteInfo["apiKey"] = sys.argv[3]
    siteInfo["lat"] = sys.argv[4]
    siteInfo["lon"] = sys.argv[5]
    
if (len(sys.argv) == 2):
    currentInfo = database.getSiteInfo(siteInfo["id"])
    print currentInfo
else:
    database.setSiteInfo(siteInfo)
    print "added/updated."



